---
- name: Configurar servidor de bando de dados
  hosts: db01

  user: vagrant
  become: true
  vars_files:
     - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "andredevops"
  tasks:
    - name: Configurar hots do lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.2.2 control-node
        - 192.168.2.3 app01
        - 192.168.2.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql

