pipeline {
    agent any
    stage ('build da imagem docker') {
        steps{
            sh 'docker build -t devops/app .'
        }
    }
    stage('subir docker compose - redis e app'){
        steps {
            sh 'docker-compose up --build -d'
        }
    }
    stage('sleep de subida dos containers'){
        steps{
            sh 'sleep 10'
        }
    }
    stage('teste app'){
        steps{
            sh 'teste-app.sh'
        }
    }
}